baseurl = "https://ag-ifpb.github.io/blog"
title = "AGBlog"
languagecode = "pt-br"
theme = "purehugo"
categories = ["welcome", "golang", "java"]

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  hideshareoptions = true
  author = "Ari Garcia"
  description = "Blog's Ari Garcia"
  githubname = "aristofanio"
  twittername = "ag-ifpb"

