baseurl = "https://ag-ifpb.github.io/blog"
title = "AGBlog"
languageCode = "pt-br"
theme = "purehugo"
#disqusShortname = "xxxx"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  hide_share_options = true
  author = "Ari Garcia"
  description = "Blog's Ari Garcia"
  github_name = "aristofanio"
  twitter_name = "aristofanioga"

