baseurl = "https://ag-ifpb.github.io/blog"
title = "AGBlog"
languageCode = "pt-br"
theme = "purehugo"
#disqusShortname = "xxxx"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  hideShareOptions = true
  author = "Ari Garcia"
  description = "Blog's Ari Garcia"
  githubname = "aristofanio"
  twittername = "aristofanioga"

